CREATE TABLE artists
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(255) NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 name VARCHAR(255) NOT NULL,
 bio VARCHAR,
 location VARCHAR(255),
 created_at TIMESTAMP,
 updated_at TIMESTAMP);
