CREATE TABLE artists
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 name VARCHAR(255) NOT NULL UNIQUE,
 bio VARCHAR,
 location VARCHAR(255),
 instruments VARCHAR(255),
 created_at TIMESTAMP,
 updated_at TIMESTAMP,
 has_image BOOLEAN DEFAULT FALSE);

INSERT INTO artists (username, password_hash, name, bio, location, instruments, created_at, updated_at, has_image)
VALUES ('anthony_kiedis', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Anthony Kiedis', 
        'Anthony Kiedis (born November 1, 1962) is an American musician, singer, songwriter, rapper, and actor. He is best known as a founding member and the lead vocalist of the Red Hot Chili Peppers and has appeared on every album released by the band. Kiedis and his fellow band members were inducted into the Rock and Roll Hall of Fame in 2012.',
        'Los Angeles',
        'Singer',
         NOW(),
         NOW(),
         TRUE),
       ('flea', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Flea', 
        'Michael Peter Balzary (born 16 October 1962), known professionally as Flea, is an Australian-American musician and actor. He is best known as a founding member and the bassist of the rock band Red Hot Chili Peppers and has appeared on every album released by the band. Flea incorporates elements of funk (including slap bass), psychedelic, punk, and hard rock in his style of playing. In 2012, he and the other members of Red Hot Chili Peppers were inducted into the Rock and Roll Hall of Fame.',
        'Los Angeles',
        'Bass guitar',
         NOW(),
         NOW(),
         TRUE),
       ('john_frusciante', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'John Frusciante', 
        'John Anthony Frusciante ( born March 5, 1970) is an American musician, singer, songwriter, and producer best known as the lead guitarist of the rock band Red Hot Chili Peppers across three stints (1988–1992, 1998–2009, 2019–present). He has recorded five studio albums with them. Frusciante was inducted into the Rock and Roll Hall of Fame as a member of the Red Hot Chili Peppers on April 14, 2012.',
        'Los Angeles',
        'Guitar',
         NOW(),
         NOW(),
         TRUE),
       ('chad_smith', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Chad Smith', 
        'Chad Gaylord Smith (born October 25, 1961) is an American musician who is the current drummer of the band Red Hot Chili Peppers, which he joined in 1988. The group was inducted into the Rock and Roll Hall of Fame in 2012.',
        'Los Angeles',
        'Drums',
         NOW(),
         NOW(),
         TRUE),
       ('maynard_keenan', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Maynard Keenan', 
        'Maynard James Keenan (born James Herbert Keenan; April 17, 1964) is an American singer-songwriter. He is the lead singer and primary lyricist of the rock bands Tool and A Perfect Circle with whom he has released five and four studio albums, respectively. In 2003, he created Puscifer as a side project, with which he has released three studio albums.',
        'Arizona',
        'Singer',
         NOW(),
         NOW(),
         TRUE),
       ('danny_carey', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Danny Carey', 
        'Daniel Edwin Carey (born May 10, 1961) is an American musician and songwriter best known for his work in American rock band Tool. Carey has laid claim to various drumming techniques that use sacred geometric figures such as the unicursal hexagram. The final product is very recognizable, fluent drumming.',
        'Los Angeles',
        'Drums',
         NOW(),
         NOW(),
         TRUE),
       ('adam_jones', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Adam Jones', 
        'Adam Thomas Jones (born January 15, 1965) is a three-time Grammy Award-winning American musician and visual artist, best known as the guitarist for Tool. Jones has been rated the 75th Greatest Guitarist of all time by the Rolling Stone. With experience in special effects and set design in the Hollywood film industry, Jones is also the director of the majority of Tools music videos.',
        'Los Angeles',
        'Guitar',
         NOW(),
         NOW(),
         TRUE),
       ('justin_chancellor', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Justin Chancellor', 
        'Justin Gunnar Walter Chancellor (born 19 November 1971) is an English musician formerly in the band Peach but best known as the bass player for progressive metal band Tool. Peach released an album and supported Tool in the early 1990s in England. In September 1995, Chancellor moved to the United States and joined Tool full-time to replace Paul D Amour who departed after the bands first full-length album. Chancellor has remained with Tool since for four albums and several tours.',
        'London',
        'Bass guitar',
         NOW(),
         NOW(),
         TRUE),
       ('dave_gahan', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Dave Gahan', 
        'Dave Gahan (born David Callcott; 9 May 1962) is an English singer-songwriter, best known as the lead singer of the electronic band Depeche Mode since their debut in 1980. Gahan is known for his "commanding presence on stage" and his "huge, deep baritone voice".',
        'London',
        'Singer',
         NOW(),
         NOW(),
         TRUE),
       ('martin_gore', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Martin Gore', 
        'Martin Lee Gore (born 23 July 1961) is an English songwriter, musician, singer, record producer, remixer, and DJ. He is one of the founding members of the synth-pop band Depeche Mode and is its primary songwriter. Gore is the bands keyboardist and guitar player, contributes backing vocals, and occasionally provides lead vocals. Gore possesses a tenor singing voice which contrasts with Dave Gahans dramatic baritone and is also known for his flamboyant and (sometimes) androgynous stage persona. Gore has also released several solo albums and collaborated with former Depeche Mode member Vince Clarke as part of VCMG.',
        'London',
        'Guitar,Keyboard,Singer',
         NOW(),
         NOW(),
         TRUE),
       ('andy_fletcher', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Andy Fletcher', 
        'Andrew John Leonard Fletcher (born 8 July 1961), popularly known as "Fletch", is an English keyboard player and one of the founding members of the electronic band Depeche Mode.',
        'London',
        'Keyboard',
         NOW(),
         NOW(),
         TRUE),
       ('florence_welch', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Florence Welch', 
        'Florence Leontine Mary Welch (born 28 August 1986) is an English singer and songwriter. She is the vocalist and primary songwriter of the indie rock band Florence and the Machine. In 2018, Welch released a book titled Useless Magic, a collection of lyrics and poems written by Welch, along with illustrations.',
        'London',
        'Singer',
         NOW(),
         NOW(),
         TRUE),
       ('isabella_summers', 
        'bcrypt+sha512$2bc0ff517f2afefa2b14194d73b2ad65$12$a40b2ccf25c81a2bc993bc4fdf0dd245b019cd0cad89583c', 
        'Isabella Summers', 
        'Isabella Janet Florentina Summers (born 31 October 1980) is an English musician, singer, songwriter, producer, remixer and member of English indie rock band Florence and the Machine. As well as being the keyboard player for the group, Summers has five co-writing credits on the critically acclaimed, BRIT Award-winning Lungs and three on the album Ceremonials. She has three songs on the album How Big, How Blue, How Beautiful: "Delilah", "How Big, How Blue, How Beautiful" and "Which Witch", including two productions on the deluxe version.',
        'London',
        'Keyboard',
         NOW(),
         NOW(),
         TRUE);

