CREATE TABLE bands
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 bio VARCHAR,
 location VARCHAR(255),
 genres VARCHAR(255),
 created_at TIMESTAMP,
 updated_at TIMESTAMP,
 owner_id INT NOT NULL,
 FOREIGN KEY (owner_id) REFERENCES artists (id) ON DELETE CASCADE ON UPDATE CASCADE,
 has_image BOOLEAN DEFAULT FALSE);

INSERT INTO bands (name, bio, location, genres, created_at, updated_at, owner_id, has_image)
VALUES ('Red Hot Chili Peppers',
        'Red Hot Chili Peppers are an American rock band formed in Los Angeles in 1983. The groups musical style primarily consists of alternative rock with an emphasis on funk, as well as elements from other genres such as punk rock and psychedelic rock. Red Hot Chili Peppers are one of the best-selling bands of all time with over 80 million records sold worldwide, they have been nominated for sixteen Grammy Awards, of which they have won six. In 2012, they were inducted into the Rock and Roll Hall of Fame. Discography: The Red Hot Chili Peppers (1984), Freaky Styley (1985), The Uplift Mofo Party Plan (1987), Mothers Milk (1989), Blood Sugar Sex Magik (1991), One Hot Minute (1995), Californication (1999), By the Way (2002), Stadium Arcadium (2006), Im with You (2011), The Getaway (2016).',
        'Los Angeles',
        'Funk rock,Alternative rock,Funk metal,Rap rock',
        NOW(),
        NOW(),
        1,
        TRUE),
       ('Tool',
        'Tool is an American rock band from Los Angeles formed in 1990. To date, the band has released five studio albums, one EP and one box set. They emerged with a heavy metal sound on their first studio album, Undertow (1993), and became a dominant act in the alternative metal movement with the release of their follow-up album Ænima in 1996. Their efforts to unify musical experimentation, visual arts, and a message of personal evolution continued with Lateralus (2001) and 10,000 Days (2006), gaining critical acclaim and international commercial success. Their fifth studio album, Fear Inoculum, their first in thirteen years, was released on August 30, 2019 to widespread critical acclaim. Prior to its release, the band had sold over 13 million albums in the US alone. Tool has won three Grammy Awards, performed worldwide tours, and produced albums topping the charts in several countries.',
        'Los Angeles',
        'Alternative metal,Art rock,Post-metal,Progressive metal,Progressive rock',
        NOW(),
        NOW(),
        5,
        TRUE),
       ('Depeche Mode',
        'Depeche Mode are an English electronic music band formed in Basildon, Essex in 1980. Depeche Mode has had 54 songs in the UK Singles Chart and 17 top 10 albums in the UK chart; they have sold more than 100 million records worldwide. Discography: Speak & Spell (1981), A Broken Frame (1982), Construction Time Again (1983), Some Great Reward (1984), Black Celebration (1986), Music for the Masses (1987), Violator (1990), Songs of Faith and Devotion (1993), Ultra (1997), Exciter (2001), Playing the Angel (2005), Sounds of the Universe (2009), Delta Machine (2013), Spirit (2017)',
        'London',
        'Synth-pop,New wave,Dance-rock,Electronic rock,Alternative rock,Industrial,Industrial rock,Synthrock',
        NOW(),
        NOW(),
        9,
        TRUE),
       ('Florence + the Machine',
        'Florence and the Machine (stylised as Florence + the Machine) are an English indie rock band that formed in London in 2007, consisting of vocalist Florence Welch, keyboardist Isabella Summers, guitarist Rob Ackroyd, harpist Tom Monger, and a collaboration of other musicians. The bands music received praise across the media, especially from the BBC, which played a large part in their rise to prominence by promoting Florence and the Machine as part of BBC Introducing. At the 2009 Brit Awards they received the Brit Awards "Critics Choice" award. The bands music is renowned for its dramatic and eccentric production and also Welchs powerful vocal performances.',
        'London',
        'Indie rock,Indie pop,Baroque pop,Chamber pop,Art rock,Art pop,Neo soul,Folk',
        NOW(),
        NOW(),
        12,
        TRUE);